---
title: "SOCAT-GLODAP"
author: "Jean-Pierre Gattuso"
date: "2/9/2021"
output: html_document
---

```{r setup, include=FALSE}
# Start with common project code
# Find who is the user and define the pCloud path
if (Sys.getenv("LOGNAME") == "gattuso"){
  pCloud_path = "~/pCloud\ Drive/"
} else {
  pCloud_path = "~/pCloudDrive/" 
}
library(tidyverse)
library(data.table) # For 'fread'
library(doParallel) # For using multiple cores
```

```{r read socat}
#read tsv file; done only once
# dat <- read_tsv(file = paste0(pCloud_path, "FACE-IT_data/socat/SOCATv2020.tsv"), skip = 6360, n_max = Inf) 
# write_rds(dat, file = paste0(pCloud_path, "FACE-IT_data/socat/SOCATv2020.rds"))

#read rds file (quicker)
# system.time(
# dat_fread <- data.table::fread(input = paste0(pCloud_path, "FACE-IT_data/socat/SOCATv2020.tsv"), skip = 6362, nThread = 10, fill = TRUE) %>%
#   dplyr::select(yr, mon, day, `longitude [dec.deg.E]`, `latitude [dec.deg.N]`, `pCO2water_SST_wet [uatm]`)
# ) # 20 seconds
# system.time(
# dat_readr <- readr::read_tsv(file = paste0(pCloud_path, "FACE-IT_data/socat/SOCATv2020.tsv"), skip = 6361) %>%
#   dplyr::select(yr, mon, day, `longitude [dec.deg.E]`, `latitude [dec.deg.N]`, `pCO2water_SST_wet [uatm]`)
# ) # 64 seconds
# system.time(
dat <- read_rds(file = paste0(pCloud_path, "FACE-IT_data/socat/SOCATv2020.rds")) %>%
  dplyr::select(yr, mon, day, `longitude [dec.deg.E]`, `latitude [dec.deg.N]`, `pCO2water_SST_wet [uatm]`)
# ) # 126 seconds
all <- dat %>% # whole ocean
  dplyr::filter(!is.na(`pCO2water_SST_wet [uatm]`)) # remove NAs
arctic <- dat %>% 
  dplyr::filter(`latitude [dec.deg.N]` > 66, !is.na(`pCO2water_SST_wet [uatm]`))
```

SOCAT v2020 has `r nrow(all)` records of pCO2water_SST_wet [uatm], including `r nrow(arctic)`, or `r 100*nrow(arctic)/nrow(all)`%, in the Arctic Ocean (North of 66°N). According to http://www.physicalgeography.net/fundamentals/8o.html, the surface area of the world ocean and the Arctic Ocean are, respectively, 361,132,000 and 14,056,000 km2. The Arctic Ocean is therefore `r 100  * 14056000 / 361132000`% of the ocean.

