---
title: "Meta_databases"
output: html_document
date: "2023-04-12"
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.align = 'center',
                      echo = FALSE, warning = FALSE, message = FALSE, 
                      eval = TRUE, tidy = FALSE)

# Libraries
library(tidyverse)
library(kableExtra) # For formatting static tables
library(DT) # For interactive tables

# Table column names
DT_cols <- c("Type", "Driver", "Date", "Source", "Citation", "Notes")

# Datatable options for all tables
options(DT.options = list(pageLength = 5,
                          deferRender = TRUE,
                          scrollY = 400,
                          scrollCollapse = TRUE,
                          lengthMenu = c(5, 10, 25, 50, 100)))
```


```{r isfjorden-meta-data}

# glaucous gull population
kong_glgu <- data.frame(type = "CTD",
                         data_name = "Biomass: glaucous gull",
                         date_range = "2005 to 2021",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/glaucous-gull/">MOSJ</a>',
                         citation = '<a onclick="alert(\'Norwegian Polar Institute (2022). Glaucous gull population, as percentage of the average in the colony. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/glaucous-gull.html\');">NPI (2022)</a>',
                         note = NA)

# polar pod population
barents_polarpod <- data.frame(type = "CTD",
                         data_name = "Biomass: polar cod",
                         date_range = "1986 to 2021",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/biomass-of-polar-cod-in-the-barents-sea//">MOSJ</a>',
                         citation = '<a onclick="alert(\'Norwegian Polar Institute (2022). Glaucous gull population, as percentage of the average in the colony. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: Institute of Marine Research (2022). Biomass of polar cod in the Barents Sea. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/polar-cod.html\');">NPI (2022)</a>',
                         note = NA)

# capelin population
barents_capelin <- data.frame(type = "CTD",
                         data_name = "Biomass: capelin",
                         date_range = "1973 to 2021",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/capelin-stock-in-the-barents-sea//">MOSJ</a>',
                         citation = '<a onclick="alert(\'Institute of Marine Research (2022). Capelin stock in the Barents Sea. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/capelin.html"\');">NPI (2022)</a>',
                         note = NA)

# common eiders population
barents_eiders <- data.frame(type = "CTD",
                         data_name = "Biomass: common eiders",
                         date_range = "1981 to 2022",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/common-eider/">MOSJ</a>',
                         citation = '<a onclick="alert(\'Norwegian Polar Institute (2022). Breeding population of common eiders in Kongsfjorden, number of breeding pairs. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/common-eider.html\');">NPI (2022)</a>',
                         note = NA)

# seabird population
kong_seabirds <- data.frame(type = "CTD",
                         data_name = "Biomass: seabirds",
                         date_range = "2011 to 2018",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://data.npolar.no/dataset/0ea572cd-1e4c-47a3-b2a5-5d7cc75aaeb4">NPDC</a>',
                         citation = '<a onclick="alert(\'Descamps, S., & Strøm, H. (2021). Seabird monitoring data from Svalbard, 2009-2018 [Data set]. Norwegian Polar Institute. https://doi.org/10.21334/npolar.2021.0ea572cd\');">Descamps and Strøm (2021)</a>',
                         note = NA)

# golden redfish population
barents_golden_redfish <- data.frame(type = "CTD",
                         data_name = "Biomass: golden redfish",
                         date_range = "1986 to 2019",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/golden-redfish-stock-in-the-barents-sea/">MOSJ</a>',
                         citation = '<a onclick="alert(\'Institute of Marine Research (2023). Stock of golden redfish in the Barents Sea. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL:
 https://mosj.no/en/indikator/fauna/marine-fauna/golden-redfish-stock-in-the-barents-sea/\');">NPI (2022)</a>',
                         note = NA)

# ivory gull population
svalbard_ivorygull <- data.frame(type = "CTD",
                         data_name = "Biomass: ivory gull",
                         date_range = "2009 to 2021",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/ivory-gull/">MOSJ</a>',
                         citation = '<a onclick="alert(\'Norwegian Polar Institute (2022). The number of breeding pairs of ivory gulls in Svalbard. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/ismaake.html\');">NPI (2022)</a>',
                         note = NA)

# beaked redfish population
barents_beakedredfish <- data.frame(type = "CTD",
                         data_name = "Biomass: beaked redfish",
                         date_range = "1992 to 2020",
                         URL = '<a target="_blank" rel="noopener noreferrer" href="https://mosj.no/en/indikator/fauna/marine-fauna/bestanden-av-snabeluer-i-barentshavet/">MOSJ</a>',
                         citation = '<a onclick="alert(\'Institute of Marine Research (2022). Stock of beaked redfish in the Barents Sea. Environmental monitoring of Svalbard and Jan Mayen (MOSJ). URL: http://www.mosj.no/en/fauna/marine/deep-sea-redfish.html\');">NPI (2022)</a>',
                         note = NA)






# Bind them together
metadata_isfjorden <- rbind(kong_glgu, barents_polarpod, barents_capelin, barents_eiders, kong_seabirds, barents_golden_redfish, svalbard_ivorygull, barents_beakedredfish)
```

```{r isfjorden-meta-data-table}
DT::datatable(metadata_isfjorden, rownames = FALSE, escape = FALSE, colnames = DT_cols,
              caption = "Table 2: Data that have been accumulated for Isfjorden. Full meta-database available via 'Data' -> 'Meta-database' tab above.")
```

<br>

